package com.example.rta.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "cont_editorial_sentence")
public class ContentEditorialSentence {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", nullable = false)
	private Integer id;

	@Column(name = "sentence", length = 1000, nullable = false)
	private String sentence;

	@Column(name = "table_name", length = 30, nullable = false)
	private String tableName;

	@Column(name = "language", length = 5)
	private String language;

	protected ContentEditorialSentence() {
	}

	// Convenience constructor for creating new instances (do NOT accept id).
	public ContentEditorialSentence(String sentence, String tableName, String language) {
		this.sentence = sentence;
		this.tableName = tableName;
		this.language = language;
	}


	public Integer getId() {
		return id;
	}

	// Keep setter non-public to avoid accidental id assignment; the id is generated by JPA.
	protected void setId(Integer id) {
		this.id = id;
	}

	public String getSentence() {
		return sentence;
	}

	public void setSentence(String sentence) {
		this.sentence = sentence;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}
}
