package com.example.rta.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

@Entity
@Table(name = "mad_libelle")
public class Libelle {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", nullable = false)
	private Integer id;

	@Column(name = "libelle_original", nullable = false)
	private String libelleOriginal;

	protected Libelle() {
	}

	// Convenience constructor without id for creating new entities
	public Libelle(String libelleOriginal) {
		this.libelleOriginal = libelleOriginal;
	}


	public Integer getId() {
		return id;
	}

	// Keep setter non-public to avoid accidental id assignment; the id is generated by JPA.
	protected void setId(Integer id) {
		this.id = id;
	}

	public String getLibelleOriginal() {
		return libelleOriginal;
	}

	public void setLibelleOriginal(String libelleOriginal) {
		this.libelleOriginal = libelleOriginal;
	}
}
